name: Steve
main: com.steve.Main
version: 1.0
commands:
  test1:
    description: test1
    usage: /<command>
  test2:
    description: test2
    usage: /<command>
  test3:
    description: test3
    usage: /<command>