main: com.steve.Main
name: Steve
version: "1.0"
description: "Steve description"
api-version: "1.16"
author: "lord steve"
commands:
  playerdata:
    aliases: pd
    description: modify playerdata
    usage: /<command> set [name] <field> <value>
  tiptoe:
    description: tiptoe
    usage: /<command> 1/2/3
  friend:
    description: friend parent command
    usage: /<command> list, /friend add <name>
  tnttag:
    description: boom
    usage: /<command>
  game:
    description: game management
    usage: /<command> start