main: com.steve.Main
name: Steve
version: "1.0"
description: "Steve description"
api-version: "1.16"
author: "lord steve"
commands:
  playerdata:
    aliases: pd
    description: modify playerdata
    usage: /<command> set [name] <field> <value>
  friend:
    aliases: f
    description: friend parent command
    usage: /<command> list, /friend add <name>
  travel:
    aliases: t
    description: travel
    usage: /<command> [force]
  editor:
    aliases: edit
    description: editor world
    usage: /<command> [save]
  spectate:
    aliases: spec
    description: spectate ongoing game
    usage: /<command>
  game:
    aliases: g
    description: game-specific commands
    usage: /<command> (usage varies)
  lobby:
    aliases: l
    description: lobby world
    usage: /<command>
  end:
    aliases: e
    description: end game
    usage: /<command>
  stoptasks:
    description: stop game tasks
    usage: /<command>