name: Steve
version: "1.0"
author: "lord steve"
main: com.steve.Main
commands:
  playerdata:
    description: modify playerdata manually
    usage: /<command>
  spawnplatform:
    description: ok
    usage: /<command>
  generatemaze:
    description: ok
    usage: /<command>
  friend:
    description: friend parent command
    usage: /<command>
  tnthelmet:
    description: boom
    usage: /<command>
  test1:
    description: test
    usage :/<command>
  test2:
    description: test
    usage :/<command>
  test3:
    description: test
    usage :/<command>