name: Steve
version: "1.0"
author: "lord steve"
main: com.steve.Main
commands:
  spawnplatform:
    description: ok
    usage: /<command>
  generatemaze:
    description: ok
    usage: /<command>
  friend:
    description: friend parent command
    usage: /<command>