name: Steve
version: "1.0"
author: "lord steve"
main: com.steve.Main
commands:
  playerdata:
    description: modify playerdata
    usage: /playerdata set [name] <field> <value>
  tiptoe:
    description: tiptoe
    usage: /tiptoe 1/2/3
  friend:
    description: friend parent command
    usage: /friend list, /friend add <name>
  tnttag:
    description: boom
    usage: /tnttag