main: com.steve.Main
name: Steve
version: "1.0"
description: "Steve description"
api-version: "1.16"
author: "lord steve"
commands:
  playerdata:
    aliases: pd
    description: modify playerdata
    usage: /<command> set [name] <field> <value>
  friend:
    description: friend parent command
    usage: /<command> list, /friend add <name>
  travel:
    description: travel
    usage: /<command> [force]
  editor:
    description: editor world
    usage: /<command> [save]
  game:
    description: game world
    usage: /<command>
  lobby:
    description: lobby world
    usage: /<command>
  end:
    description: end game
    usage: /<command>
  stoptasks:
    description: stop game tasks
    usage: /<command>
  tnttag:
    description: tnt tag
    usage: /<command>
  tiptoe:
    description: tip toe
    usage: /<command> 1/2/3
  jump:
    description: jump showdown
    usage: /<command> speed <number>